#title: Blog
#theme: jekyll-theme-minimal
title:            Cici's notebook
remote_theme:     sighingnow/jekyll-gitbook
collections:
  pages:
    output: true
    permalink: /:collection/:path/

plugins:
    - jekyll-paginate
    - jekyll-gist
    - jekyll-feed
    - jekyll-include-cache
    - jekyll-seo-tag
#打開toc 把markdown變成html
toc:
    enabled: true

#以下跟程式碼區塊有關
#markdown:         kramdown
#kramdown:
#  auto_ids:               true
#  input:                  GFM
#  math_engine:            mathjax
#  smart_quotes:           lsquo,rsquo,ldquo,rdquo
#  toc_levels:             1..6
#  syntax_highlighter:     rouge
#  syntax_highlighter_opts:
#    guess_lang:           true

#############################
#markdown: redcarpet
#highlighter: pygments 
 
#################################################
#pygments:        true
#markdown:        redcarpet
#redcarpet:
#  extensions: [:smart, :fenced_code, :gh_blockcode] 
##################################################
#kramdown:
#  enable_coderay: true
#  syntax_highlighter: coderay
#  syntax_highlighter_opts: 
#    line_numbers: span
#    bold_every: 5

#程式碼的預設樣式(可參考下方修改樣式)
#https://spsarolkar.github.io/rouge-theme-preview/
kramdown:
  parse_block_html: true
  parse_span_html: true
syntax_highlighter_style: base16 

#設定預設值
defaults:
  - scope:
      path: "" #所有目錄
      type: "pages" # _pages目錄下的所有文意
    values:
      layout: "post" #預設layout
      author: "Cici li" #預設作者    
  - scope:
      path: "assets/img" #圖片位置設定，參考jekyll static file的設定
    values:
      image: true #把assets/img目錄下的所有圖片的image屬性設為true

#baseurl: /blog #網站的目錄
imgurl: /assets/img
locale: "zh-TW" # 自己的地區
description: "Cici's notebook." # 網站的描述
url: "https://newcici7777.github.io" # 自己部落格的網址
route: ""
extra_css: 
  - assets/custom_css/code.css # 自己修改程式碼區塊css，不同的theme顯示的程式碼css與文字
extra_footer_js:
  - assets/js/side_bar.js
google_site_verification: 65zgvtfJFNDdKge0tDpfLKShsOrANSZ0hsdp1prfxzs
include:
  - sitemap.xml